create table if not exists public.booking_attribution_events (
  id bigint generated by default as identity primary key,
  respond_contact_id text not null,
  booking_key text not null unique,
  external_booking_id text,
  booked_at timestamptz not null default now(),
  meeting_start_at timestamptz,
  source_platform text not null default 'unknown',
  source_type text not null default 'unknown',
  campaign_id text,
  campaign_name text,
  ad_id text,
  ad_name text,
  ad_url text,
  attribution_data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists booking_attribution_booked_at_idx
on public.booking_attribution_events (booked_at desc);

alter table public.booking_attribution_events enable row level security;
