create table if not exists public.booking_failure_events (
  id bigint generated by default as identity primary key,
  respond_contact_id text not null,
  attempt_key text not null,
  failure_type text not null,
  failure_phase text not null,
  seller_slug text,
  offered_start_at timestamptz,
  booking_team text,
  pending_field text,
  error_message text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists booking_failure_events_created_at_idx
  on public.booking_failure_events (created_at desc);

create index if not exists booking_failure_events_contact_idx
  on public.booking_failure_events (respond_contact_id, created_at desc);

create index if not exists booking_failure_events_type_idx
  on public.booking_failure_events (failure_type, created_at desc);

alter table public.booking_failure_events enable row level security;
