create table if not exists public.respond_reply_events (
  id bigint generated by default as identity primary key,
  respond_contact_id text not null,
  respond_message_id text,
  channel_id text,
  message_type text not null default 'text',
  message_preview text,
  replied_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create unique index if not exists respond_reply_events_message_id_idx
  on public.respond_reply_events (respond_message_id)
  where respond_message_id is not null;

create index if not exists respond_reply_events_replied_at_idx
  on public.respond_reply_events (replied_at desc);

create index if not exists respond_reply_events_contact_id_idx
  on public.respond_reply_events (respond_contact_id);

alter table public.respond_reply_events enable row level security;
