create table if not exists public.booking_attempts (
  attempt_key text primary key,
  respond_contact_id text not null,
  seller_slug text not null,
  appointment_start_at timestamptz not null,
  status text not null default 'processing'
    check (status in ('processing', 'confirmed', 'failed')),
  lease_owner text,
  lease_expires_at timestamptz,
  booked_result jsonb,
  last_error text,
  attempt_count integer not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists booking_attempts_contact_idx
  on public.booking_attempts (respond_contact_id, created_at desc);
create index if not exists booking_attempts_lease_idx
  on public.booking_attempts (status, lease_expires_at);

create table if not exists public.booking_reconciliation_jobs (
  id bigint generated by default as identity primary key,
  attempt_key text not null unique references public.booking_attempts(attempt_key) on delete cascade,
  respond_contact_id text not null,
  payload jsonb not null default '{}'::jsonb,
  status text not null default 'pending'
    check (status in ('pending', 'processing', 'completed', 'failed')),
  attempts integer not null default 0,
  next_attempt_at timestamptz not null default now(),
  lease_owner text,
  lease_expires_at timestamptz,
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  completed_at timestamptz
);

create index if not exists booking_reconciliation_due_idx
  on public.booking_reconciliation_jobs (status, next_attempt_at);

create table if not exists public.booking_funnel_events (
  id bigint generated by default as identity primary key,
  event_key text not null unique,
  respond_contact_id text not null,
  event_type text not null,
  attempt_key text,
  seller_slug text,
  appointment_start_at timestamptz,
  booking_team text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists booking_funnel_events_contact_idx
  on public.booking_funnel_events (respond_contact_id, created_at desc);
create index if not exists booking_funnel_events_type_idx
  on public.booking_funnel_events (event_type, created_at desc);
alter table public.booking_attempts enable row level security;
alter table public.booking_reconciliation_jobs enable row level security;
alter table public.booking_funnel_events enable row level security;

create or replace function public.acquire_booking_attempt(
  claim_attempt_key text,
  claim_contact_id text,
  claim_seller_slug text,
  claim_start_at timestamptz,
  claim_owner text,
  claim_lease_seconds integer default 120
) returns public.booking_attempts
language plpgsql security definer set search_path = public
as $$
declare result public.booking_attempts;
begin
  insert into public.booking_attempts (
    attempt_key, respond_contact_id, seller_slug, appointment_start_at,
    lease_owner, lease_expires_at
  ) values (
    claim_attempt_key, claim_contact_id, claim_seller_slug, claim_start_at,
    claim_owner, now() + make_interval(secs => greatest(claim_lease_seconds, 30))
  )
  on conflict (attempt_key) do update set
    status = case
      when booking_attempts.status = 'confirmed' then 'confirmed'
      else 'processing'
    end,
    lease_owner = case
      when booking_attempts.status = 'confirmed' then booking_attempts.lease_owner
      else excluded.lease_owner
    end,
    lease_expires_at = case
      when booking_attempts.status = 'confirmed' then booking_attempts.lease_expires_at
      else excluded.lease_expires_at
    end,
    attempt_count = case
      when booking_attempts.status = 'confirmed' then booking_attempts.attempt_count
      else booking_attempts.attempt_count + 1
    end,
    updated_at = now()
  where booking_attempts.status = 'confirmed'
     or booking_attempts.lease_expires_at is null
     or booking_attempts.lease_expires_at <= now()
     or booking_attempts.lease_owner = excluded.lease_owner;

  select * into result from public.booking_attempts where attempt_key = claim_attempt_key;
  return result;
end;
$$;

create or replace function public.claim_booking_reconciliation_job(
  worker_id text,
  lease_seconds integer default 120
) returns setof public.booking_reconciliation_jobs
language plpgsql security definer set search_path = public
as $$
declare selected_id bigint;
begin
  select id into selected_id
  from public.booking_reconciliation_jobs
  where status in ('pending', 'processing')
    and next_attempt_at <= now()
    and (lease_expires_at is null or lease_expires_at <= now())
  order by next_attempt_at, id
  for update skip locked
  limit 1;

  if selected_id is null then return; end if;

  return query
  update public.booking_reconciliation_jobs
  set status = 'processing', lease_owner = worker_id,
      lease_expires_at = now() + make_interval(secs => greatest(lease_seconds, 30)),
      attempts = attempts + 1, updated_at = now()
  where id = selected_id
  returning *;
end;
$$;

revoke all on function public.acquire_booking_attempt(text, text, text, timestamptz, text, integer) from public;
revoke all on function public.claim_booking_reconciliation_job(text, integer) from public;
grant execute on function public.acquire_booking_attempt(text, text, text, timestamptz, text, integer) to service_role;
grant execute on function public.claim_booking_reconciliation_job(text, integer) to service_role;
